cookie:
  expiry_days: 30
  key: some_signature_key # Must be a string
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      first_name: John
      last_name: Smith
      roles: # Optional
      - admin
      - editor
      - viewer
    rbriggs:
      email: rbriggs@gmail.com
      first_name: Rebecca
      last_name: Briggs
      roles: # Optional
      - viewer
preauthorized:
  emails:
    - jsmith@gmail.com
    - rbriggs@gmail.com